/**
 * CONVERSATIONS ACTION TYPES.
 */
export const SET_CHAT_VISIBLE = 'SET_CHAT_VISIBLE';

/**
 * APP_STAGES ACTION TYPES.
 */
export const SET_APP_STAGE = 'SET_APP_STAGE';

/**
 * MESSAGES ACTION TYPES.
 */
export const FETCH_LAST_MESSAGES = 'FETCH_LAST_MESSAGES';